### ISSUE TITLE
Menu rendering fails on node with dynamic route.

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-display-bundle#195]
When user defines a dynamic route for a node (e.g. `/Path/with/{parameter}`) and defines the `Display in menu` option tu true, then the menu rendering fails as it tries to generate an URL without having all mandatory parameters.

**Comment by nicolasThal** [comment]
Maybe, a validator should be added

**Comment by Thiblef** [comment]
Fixed in PR https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1450
