### ISSUE TITLE
Possible 404 error due on usage of both "status.published" and "currentlyPublished" node properties

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-display-bundle#206]
A new "currentlyPublished" property has been added to nodes, but, as it is not yet used everywhere, it leads to some errors.
The MenuStrategy fetch nodes filtering on true value of "status.published" property, but the NodeController of front bundle only renders node having "currentlyPublished" at true. As nodes created before the addition of "currentlyPublished" property can be in menu, it displays links that leads to a 404.

**Comment by alavieille** [comment]
This is fixed in this PR https://trello.com/c/747FlWOs/1935-1-etq-ufront-le-menu-strategy-utilise-currentlypublished-et-non-status-published
