### ISSUE TITLE
Rename Interface for icon

### ISSUE THREAD

**Issue by KevinArtus** [open-orchestra/open-orchestra-display-bundle#241]
## Informations

**Orchestra Version** : 1.1.2

**Issue Type**: 

- [ ] Bug
- [ ] Feature request
- [x] Question
### Actual behavior

When we wanna add a class to display a icon for a block, we have to implement DisplayInterface.
### Expected behavior

To be coherent with the DisplatBlockInterface, it would be good to rename DisplayInterface to DisplayIconInterface. Btw, php doc is correct.

**Comment by alavieille** [comment]
This issue isn't longer valid with 2.0. Strategy icon is removed
